### ISSUE TITLE
z_woa13 text comments on sigma 0+2

### ISSUE THREAD

**Issue by mhrib** [HYCOM/HYCOM-tools#1]
Only text correction:
------------------
Line 84-85:
#                   =odd;  sigma-0
#                   =even; sigma-0
Sould be:
#                   =odd;  sigma-0
#                   =even;  sigma-2

Best
Mads

**Comment by awallcraft** [comment]
Thanks for the report.  z_woa13 and z_gdem* have been updated.

Alan.
