### ISSUE TITLE
Questions about converting input forcing .D files into netCDF files by using the Hycom Source Code

### ISSUE THREAD

**Issue by LXY-LSY** [HYCOM/HYCOM-tools#5]
**When I ran the file named nrl2nc, the following error occurred:**
-----------------------------------------------------------------------------------------
horout - title=NVGM 2.0 0.176c 2020 3h wndspd, MKS
          WRITING RECORD    1     FDAY = 43556.00   FDATE =20200401.0000

error in profout - from NetCDF library
nf90_put_var-pLatVarID

NetCDF: Start+count exceeds dimension bound
------------------------------------------------------------------------------------------
**I downloaded  navgem2.0_0.176c-sea_2020_03hr_wndspd.D  from [ftp://ftp.hycom.org/datasets/force/NAVGEM**](url)
------------------------------------------------------------------------------------------
I modified the following codes of the nrl2nc.f
CNAME(1) = 'wndspd'
C     READ( 5,NRL2NCDF)
I modified the following contents of the zh_hp.f 、zh_x1.f、 zh_sun.f、 zh_t3e.f、 zh_ymp.f
CFILE = 'navgem2.0_0.176c-sea_2020_03hr_wndspd.D'
C    CALL GETENV(CENV,CFILE)
------------------------------------------------------------------------------------------
**I would appreciate it if you could help me.
Thank you very much！！**

**Comment by awallcraft** [comment]
Use environment variable FOR071 to identify the input .D file.

There is a tar bundle of (old) scripts at https://www.hycom.org/tools/309-forcing-to-netcdf-converter

The following script worked for me on an unmodified nrl2nc. the "C" is ~/HYCOM-tools/bin/C or replace with '#'

`
#! /bin/csh
#
set echo
set time = 1
C
C --- Create netCDF from a NRL wndspd file
C
cd ~/force/navgem2.0_0.176c/3hourly
C
C --- Input.
C
setenv W	navgem2.0_0.176c-std_2020_03hr
C
setenv FOR071	${W}_wndspd.D
setenv CDF_FILE	${W}_wndspd.nc
#setenv CDF_INST	"Naval Research Laboratory"
C
/bin/rm -f $CDF_FILE
C
~/HYCOM-tools/force/src/nrl2nc <<E-o-D
 &NRL2NCDF
  NFLD     = 1,
  CNAME    = 'wndspd',
  FLG_SCL  = 3,             !0=input; 1=fit; 2=centered; 3=+ve; 4=-ve;
  T_BOUNDS = 0.0, 0.0       !snapshot field
 &END
E-o-D
`

**Comment by LXY-LSY** [comment]
Thank you very much for your answer.
It have set the env var "FOR071 CDF_FILE"  and the var mentioned above in csh.But it comes the same error.  Here is the whole log.

![question](https://user-images.githubusercontent.com/62001127/86100271-335c7680-baeb-11ea-9155-9976062745ef.jpg)

Could you help me again? 
Thank you very much！！！

**Comment by abozec** [comment]
Was this issue resolved ? if not I would suggest to post it on the HYCOM forum: http://groups.google.com/a/hycom.org/group/forum/
Thanks
